name = "paytm-backend"
main = "index.js"
compatibility_date = "2024-01-01"

[vars]
MONGODB_URI = "mongodb+srv://admin0:Xc3JNBza6r261VS0@cluster0.kkrub.mongodb.net/PAYTM-2"
JWT_SECRET = "12345"

[[d1_databases]]
binding = "DB"
database_name = "paytm-db"
database_id = "940352754235" 